apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: default
spec:
  limits:
    - type: PersistentVolumeClaim
      max:
        storage: 1Gi
      min:
        storage: 500Mi
      default:
        storage: 1Gi
      defaultRequest:
        storage: 500Mi
    - type: Pod
      max:
        cpu: 1000m
        memory: 1Gi
      min:
        cpu: 200m
        memory: 256Mi
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 250m
        memory: 256Mi