kind: Deployment
apiVersion: apps/v1
metadata:
  name: ittalTest-java
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ittalTest-java-label
      tier: app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ittalTest-java-label
        tier: app
    spec:
      containers:
        - name: ittalTest
          image: ittalTest/ittalTest_api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080


---
# restart 하게 되면 ssl 인증서 갱싱됨 => annotation 사용
apiVersion: v1
kind: Service
metadata:
  name: ittalTest-java
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-preserve: "true"
spec:
  type: LoadBalancer
  selector:
    app: ittalTest-java-label
  ports:
    - port: 443
      targetPort: 8080
      protocol: TCP