apiVersion: v1
kind: Service
metadata:
  name: external-data
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Endpoints
metadata:
  name: external-data
subsets:
  - addresses:
      - ip: 192.168.49.2
    ports:
      - name: http
        port: 80

---
apiVersion: apps/v1
kind: Service
metadata:
  name: lb-chk-ip
spec:
  selector:
    app: deploy-chk-ip
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer

