apiVersion: batch/v1
kind: CronJob
metadata:
  name: echo-cronjob
spec:
    schedule: "*/1 * * * *"
    jobTemplate:
        spec:
        template:
            spec:
            containers:
                - name: echo
                image: ghcr.io/subicura/echo:v1
            restartPolicy: OnFailure
            # restartPolicy: Never
            # restartPolicy: Always