apiVersion: v1
kind: Pod
metadata:
  name: pod-emptydir
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: empty-directory
          mountPath: /usr/share/nginx/html
    - name: html-builder
      image: alpine
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: empty-directory
      command: ["/bin/sh", "-c"]
      args:
        - echo "this page created on $(date + %Y-%m-%d)" > /html-dir/index.html 
          sleep infinity;

  volumes:
    # 위에 valueMounts 의 이름과 매칭
    - na칭e: empty-directory
      emptyDir: {}